### ISSUE TITLE
Custom `.toml` config files

### ISSUE THREAD

**Issue by juraj-hrivnak** [TheComputerizer/Specified-Spawning#1]
It would be cool for the organisation of the configurations if there would be the possibility to create multiple config files and subfolders.

PS: Thanks for making this :D

**Comment by TheComputerizer** [comment]
The idea was to keep things as simple as possible through only having the single config file, but I can add it as an optional feature

**Comment by juraj-hrivnak** [comment]
Nice, that would be cool

**Comment by TheComputerizer** [comment]
Added in 0.2.0
