### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ralseilii** [TheComputerizer/Specified-Spawning#4]
the crash log when using specifiedspawning-1.12.2-0.4.1.1: https://mclo.gs/poyMk6U i just have specifiedspawning,!mixinbooter-8.6 and theimpossiblelibrary-1.12.2-0.3.0 ,i only have these three mods

**Comment by ANightDazingZoroark** [comment]
i got the exact same crash report lmao, based on what ive seen there i believe its probably somethin to do w the dependency and not the mod itself

**Comment by TheComputerizer** [comment]
The issue is me using a class too early without passing it through the classloader first. It will be fixed soon

**Comment by TheComputerizer** [comment]
This should be fixed in 0.4.2

**Comment by ralseilii** [comment]
will you update forge version of 0.4.2,since only fabric version of it now

**Comment by TheComputerizer** [comment]
Oh yeah I accidentally marked it as fabric my bad I fixed it
