### ISSUE TITLE
crash when opening minecraft

### ISSUE THREAD

**Issue by ralseilii** [TheComputerizer/Specified-Spawning#5]
crash when starting minecraft,only have specifiedspawning-1.12.2-0.4.2,!mixinbooter-8.9 and theimpossiblelibrary-1.12.2-0.3.0(actually totally same situation as 0.4.1.1).
heres the report: https://mclo.gs/MirZGFl

**Comment by ralseilii** [comment]
infact since after version of specifiedspawning-1.12.2-0.3.1 version, the game crashed when opening with specifiedspawning

**Comment by TheComputerizer** [comment]
Seems like a different crash, I'll look into it

**Comment by TheComputerizer** [comment]
If you create a specifiedspawning.toml file in the config manually or copy one over from 0.3.1 it probably won't crash

**Comment by ralseilii** [comment]
> If you create a specifiedspawning.toml file in the config manually or copy one over from 0.3.1 it probably won't crash

i tried to create a specifiedspawning.toml file in the config manually but still crash
